name: 'Build devcontainer image'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      # ðŸ”¹ Build only (Forks)
      - name: Build devcontainer (no push for forks)
        if: github.event.repository.fork == true
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/daytonaio/daytona-devcontainer
          platform: linux/amd64,linux/arm64
          configFile: .devcontainer/devcontainer.build.json
          push: never

      # ðŸ”¹ Login (Only main repo)
      - name: Login to GHCR
        if: github.event.repository.fork == false
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ðŸ”¹ Build + Push (Only main repo)
      - name: Build and push devcontainer
        if: github.event.repository.fork == false
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/daytonaio/daytona-devcontainer
          cacheFrom: ghcr.io/daytonaio/daytona-devcontainer
          platform: linux/amd64,linux/arm64
          imageTag: main,latest
          configFile: .devcontainer/devcontainer.build.json
          push: always
